### ISSUE TITLE
Disable Precache

### ISSUE THREAD

**Issue by zzarcon** [jkleinsc/broccoli-serviceworker#18]
There's any way to fully disable all the cache? AKA `toolbox.precache`.

My problem with the actual behaviour is that is precaching all the assets, which in my case are > 60Mb because I have hundreds of images.

So, will be posible to remove the `urlsToPrefetch` and the `toolbox.precache` call?

Thanks!

**Comment by jkleinsc** [comment]
You can use the excludePaths option to exclude files from the precache.
From the README:
**excludePaths** - Array of paths to exclude from precache.  Files can be filtered using regular expressions.

``` JavaScript
{
  excludePaths: ['index.html', new RegExp(/.\.map$/)],
}
```

Any paths specified here with be filtered out and not included in the urlsToPrefetch.

**Comment by zzarcon** [comment]
Not really, since the [getFilesRecursively](https://github.com/jkleinsc/broccoli-serviceworker/blob/master/lib/service-worker.js#L68) is using `[ "**/*" ]` as a `globPatterns`. 

The solution is to use the `ignore` option in the [multiGlob helper](https://github.com/jkleinsc/broccoli-serviceworker/blob/master/lib/service-worker.js#L171).

I just forked the repo and did the changes, but I'm not sure if those will follow the expected behaviour of the addon, if yes I can create a PR for it :)

Changes -> https://github.com/zzarcon/broccoli-serviceworker/commit/06478c195f8612a66e5b97746f564e248bf6d67e

**Comment by jkleinsc** [comment]
@zzarcon `getFilesRecursively(srcDir, [ "**/*" ])` is using a directory that has been filtered out via broccoli-funnel that excludes any paths that are specified in excludePaths, so that directory should not have any files you wish to exclude, so the ignore option should be uneeded.  Think of it this way - your output directory is copied to a temp dir and that temp dir excludes any files/paths excluded in the excludePaths option.  Then when you do a getFilesRecursively, it is only pulling the files from that temp dir, not your output directory as a whole.

If you have an example of a specific structure that is failing to exclude, can you describe it further?

**Comment by jkleinsc** [comment]
Closing due to no response.
